version: '3.7'

volumes:
  php_socket:

services:
  database:
    container_name: database
    restart: always
    build:
      context: ./
      dockerfile: ./docker/database/Dockerfile
    volumes:
      - ./database:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
    ports:
      - 3306:3306
    working_dir: /var/lib/mysql
    networks:
      - default
  frontend:
    container_name: frontend
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/var/www
    ports:
      - 3000:3000
    working_dir: /var/www
    command: yarn dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    networks:
      - default
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    tty: true
    volumes:
      - ./backend:/var/www
      - ./docker/backend/zzz-www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf
      - php_socket:/var/run
    working_dir: /var/www
  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - backend
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - php_socket:/var/run
networks:
  default:
    driver: bridge
